export default {
  'Latin': false,
  'Rap': false,
  'Pop': false,
  'Country': false,
  'Kpop': false,
  'RnB': false,
  'Rock': false,
  'Metal': false,
  'Jazz': false,
  'Hip Hop': false,
  'Electronic Dance': false,
  'Blues': false,
  'Soul': false,
  'Punk': false,
  'Classical': false,
};